name: Minify and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.0.0
        with:
          directory: 'static'
          output: 'static'
          add_suffix: false

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Minify frontend files"
